import type {Metadata} from "next";

import {Abel} from "next/font/google";

import {Providers} from "@/lib/providers";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const abel = Abel({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Status Kit",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abel.className}`}>
        <Providers>
          <div className="bg-noise relative mx-auto grid min-h-screen w-full grid-rows-[20px_1fr_20px] gap-16 bg-white p-8 pb-20 text-[#171717] transition sm:p-10 dark:bg-[#171717] dark:text-white">
            <Header />
            <div className="mx-auto w-full max-w-7xl overflow-hidden">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
