import type {Metadata} from "next";

import {Abel} from "next/font/google";

import {Providers} from "@/lib/providers";
import "./globals.css";

const abel = Abel({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Status Kit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abel.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
